default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: FilmDev
  username: admin
  password: admin

test:
  <<: *default
  database: FilmTest
  username: admin
  password: admin

production:
  <<: *default
  database: FilmProd
  username: admin
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
